//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: greet.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate Greet_GreetingServiceClient, then call methods of this protocol to make API calls.
internal protocol Greet_GreetingServiceClientProtocol {
  func greet(_ request: Greet_GreetRequest, callOptions: CallOptions?) -> UnaryCall<Greet_GreetRequest, Greet_GreetResponse>
}

internal final class Greet_GreetingServiceClient: GRPCClient, Greet_GreetingServiceClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the greet.GreetingService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Unary call to Greet
  ///
  /// - Parameters:
  ///   - request: Request to send to Greet.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func greet(_ request: Greet_GreetRequest, callOptions: CallOptions? = nil) -> UnaryCall<Greet_GreetRequest, Greet_GreetResponse> {
    return self.makeUnaryCall(path: "/greet.GreetingService/Greet",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Greet_GreetingServiceProvider: CallHandlerProvider {
  func greet(request: Greet_GreetRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Greet_GreetResponse>
}

extension Greet_GreetingServiceProvider {
  internal var serviceName: String { return "greet.GreetingService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "Greet":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.greet(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}


// Provides conformance to `GRPCPayload`
extension Greet_Greeting: GRPCProtobufPayload {}
extension Greet_GreetRequest: GRPCProtobufPayload {}
extension Greet_GreetResponse: GRPCProtobufPayload {}
